name: Swift

on:
  pull_request:
    branches: [ master ]
    paths:
      - '**/*.swift'
      - '**/*.yml'

jobs:
  test:
    name: Run Swift Tests
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Setup Swift
      uses: swift-actions/setup-swift@v1.26.0

    - name: Run tests
      run: swift test
      working-directory: StringCatalogEnum
